<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOWSlider generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW Slider, HTML5 Gallery, Gallery Wordpress" />
	<meta name="description" content="WOWSlider created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="slider/engine1/style.css" />
	<script type="text/javascript" src="slider/engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body>
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images"><ul>
<li><img src="slider/data1/images/01.png" alt="01" style="width:980px; height:400px;" title=""  id="wows1_1"/></li>
<li><img src="slider/data1/images/02.jpg" alt="02" style="width:980px; height:400px;" title=""  id="wows1_1"/></li>
<li><img src="slider/data1/images/03.jpg" alt="03" style="width:980px; height:400px;" title=""  id="wows1_1"/></li>
<li><img src="slider/data1/images/04.png" alt="04" style="width:980px; height:400px;" title=""  id="wows1_1"/></li>
<li><img src="slider/data1/images/05.jpg" alt="05" style="width:980px; height:400px;" title=""  id="wows1_1"/></li>
<li><img src="slider/data1/images/06.jpg" alt="06" style="width:980px; height:400px;" title=""  id="wows1_1"/></li>

</ul></div>
<!-- <div class="ws_bullets"><div>
<a href="#" title="01"><img src="slider/data1/tooltips/01.JPG" style="width:112px; height:48px;" alt="01"/></a>
<a href="#" title="03"><img src="slider/data1/tooltips/03.png" style="width:112px; height:48px;" alt="03"/></a>
<a href="#" title="04"><img src="slider/data1/tooltips/04.jpg" style="width:112px; height:48px;" alt="04"/></a>
<a href="#" title="05"><img src="slider/data1/tooltips/05.jpg" style="width:112px; height:48px;" alt="05"/></a>
<a href="#" title="06"><img src="slider/data1/tooltips/06.jpg" style="width:112px; height:48px;" alt="06"/></a>
<a href="#" title="07"><img src="slider/data1/tooltips/07.jpg" style="width:112px; height:48px;" alt="07"/></a>
</div></div> -->
<span class="wsl"><a href="http://wowslider.com">Javascript Gallery</a> by WOWSlider.com v4.8</span>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="slider/engine1/wowslider.js"></script>
	<script type="text/javascript" src="slider/engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>